//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Markdetail
    {
        public int ID { get; set; }
        public Nullable<int> Roll { get; set; }
        public Nullable<int> ClassID { get; set; }
        public Nullable<decimal> ObtainMark { get; set; }
        public Nullable<decimal> OutOf { get; set; }
        public decimal Percentage { get; set; }
        public Nullable<bool> Pass { get; set; }
    
        public virtual ClassDetail ClassDetail { get; set; }
        public virtual Student Student { get; set; }
    }
}
